on:
  pull_request:
    paths:
      - "puppeteer/**"
  workflow_dispatch:

jobs:
  pull_request:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: puppeteer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Deno Lint
        run: deno lint --config deno.json

      - name: Deno Format
        run: deno fmt --config deno.json --check

      - name: Deno Test
        run: deno test -A --no-config
